blank_issues_enabled: false
contact_links:
  - name: Feature Request ðŸ’¡
    url: https://github.com/juspay/airborne/tree/main/airborne-react-native/discussions/new?category=ideas
    about: If you have a feature request, please create a new discussion on GitHub.
  - name: Discussions on GitHub ðŸ’¬
    url: https://github.com/juspay/airborne/tree/main/airborne-react-native/discussions
    about: This library works as promised but if you need help, please ask questions here.
